import localFont from "next/font/local";
import "./globals.css";
import { Providers } from '../redux/providers';
import { AntdRegistry } from '@ant-design/nextjs-registry';



export const metadata = {
  title: "trevy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
      >
        <AntdRegistry>
        <Providers>

          {children}
        </Providers>
        </AntdRegistry>
      </body>
    </html>
  );
}
